In [3]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
os.chdir("c://dewp")


from sklearn import metrics
from sklearn.metrics import classification_report,confusion_matrix

In [5]:
import warnings
warnings.filterwarnings(action="ignore")
%matplotlib inline
pd.set_option("display.max_rows", 1000) 
pd.set_option("display.max_columns", 1000)
     

In [6]:
fires = pd.read_csv("forestfires.csv")    #reading the dataset
fires.head(15)    #show the first 15 instances of dataset

X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  area
0   7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.0
1   7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.0
2   7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.0
3   8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.0
4   8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.0
5   8  6   aug  sun  92.3   85.3  488.0  14.7  22.2  29   5.4   0.0   0.0
6   8  6   aug  mon  92.3   88.9  495.6   8.5  24.1  27   3.1   0.0   0.0
7   8  6   aug  mon  91.5  145.4  608.2  10.7   8.0  86   2.2   0.0   0.0
8   8  6   sep  tue  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0   0.0
9   7  5   sep  sat  92.5   88.0  698.6   7.1  22.8  40   4.0   0.0   0.0
10  7  5   sep  sat  92.5   88.0  698.6   7.1  17.8  51   7.2   0.0   0.0
11  7  5   sep  sat  92.8   73.2  713.0  22.6  19.3  38   4.0   0.0   0.0
12  6  5   aug  fri  63.5   70.8  665.3   0.8  17.0  72   6.7   0.0   0.0
13  6  5   sep  mon  90.9  126.5  686.5   7.0  21.3  42   2.2   0.0   0.0
14  6  5   sep  wed  92.9  133.3  699.6   9.2  26.4  21   4.5   0.0   0.0

In [7]:
#show the last 10 instances of dataset
fires.tail(10)

X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
507  2  4   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0   0.00
508  1  2   aug  fri  91.0  166.9  752.6   7.1  25.9  41   3.6   0.0   0.00
509  5  4   aug  fri  91.0  166.9  752.6   7.1  21.1  71   7.6   1.4   2.17
510  6  5   aug  fri  91.0  166.9  752.6   7.1  18.2  62   5.4   0.0   0.43
511  8  6   aug  sun  81.6   56.7  665.6   1.9  27.8  35   2.7   0.0   0.00
512  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513  2  4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516  6  3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00

In [8]:
#changing days into numeric quantity because machine learning model deals with numbers
fires.day.replace(('mon','tue','wed','thu','fri','sat','sun'),(1,2,3,4,5,6,7), inplace=True)

#changing month into numeric quantity
fires.month.replace(('jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'),(1,2,3,4,5,6,7,8,9,10,11,12), inplace=True)

#showing first 10 instances of dataset after converting days and months into numbers
fires.head(15) 
     

X  Y  month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  area
0   7  5      3    5  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.0
1   7  4     10    2  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.0
2   7  4     10    6  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.0
3   8  6      3    5  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.0
4   8  6      3    7  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.0
5   8  6      8    7  92.3   85.3  488.0  14.7  22.2  29   5.4   0.0   0.0
6   8  6      8    1  92.3   88.9  495.6   8.5  24.1  27   3.1   0.0   0.0
7   8  6      8    1  91.5  145.4  608.2  10.7   8.0  86   2.2   0.0   0.0
8   8  6      9    2  91.0  129.5  692.6   7.0  13.1  63   5.4   0.0   0.0
9   7  5      9    6  92.5   88.0  698.6   7.1  22.8  40   4.0   0.0   0.0
10  7  5      9    6  92.5   88.0  698.6   7.1  17.8  51   7.2   0.0   0.0
11  7  5      9    6  92.8   73.2  713.0  22.6  19.3  38   4.0   0.0   0.0
12  6  5      8    5  63.5   70.8  665.3   0.8  17.0  72   6.7   0.0   0.0
13  6  5      9    1  90.9  126.5  686.5   7.0  21.3  42   2.2   0.0   0.0
14  6  5      9    3  92.9  133.3  699.6   9.2  26.4  21   4.5   0.0   0.0

In [9]:
#generate descriptive statistics of each attribute
fires.describe().T

count        mean         std   min    25%     50%     75%      max
X      517.0    4.669246    2.313778   1.0    3.0    4.00    7.00     9.00
Y      517.0    4.299807    1.229900   2.0    4.0    4.00    5.00     9.00
month  517.0    7.475822    2.275990   1.0    7.0    8.00    9.00    12.00
day    517.0    4.259188    2.072929   1.0    2.0    5.00    6.00     7.00
FFMC   517.0   90.644681    5.520111  18.7   90.2   91.60   92.90    96.20
DMC    517.0  110.872340   64.046482   1.1   68.6  108.30  142.40   291.30
DC     517.0  547.940039  248.066192   7.9  437.7  664.20  713.90   860.60
ISI    517.0    9.021663    4.559477   0.0    6.5    8.40   10.80    56.10
temp   517.0   18.889168    5.806625   2.2   15.5   19.30   22.80    33.30
RH     517.0   44.288201   16.317469  15.0   33.0   42.00   53.00   100.00
wind   517.0    4.017602    1.791653   0.4    2.7    4.00    4.90     9.40
rain   517.0    0.021663    0.295959   0.0    0.0    0.00    0.00     6.40
area   517.0   12.847292   63.655818   0.0    0.0    0.52    6.57  1090.84

In [10]:
#given area of land burnt, but we have to predict if there is fire or not so changing values of area to 0 and 1 only
#here 0 represet there is not fire and 1 represent fire, changing all values of area which are greater than 0 to 1
fires['area'].values[fires['area'].values > 0] = 1

#renaming the area attribute to output for clear understanding
fires = fires.rename(columns={'area': 'output'})
fires.head(5)
     

X  Y  month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  output
0  7  5      3    5  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0     0.0
1  7  4     10    2  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0     0.0
2  7  4     10    6  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0     0.0
3  8  6      3    5  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2     0.0
4  8  6      3    7  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0     0.0

In [11]:
#Compute pairwise correlation of columns
fires.corr()


X         Y     month       day      FFMC       DMC        DC  \
X       1.000000  0.539548 -0.065003 -0.024922 -0.021039 -0.048384 -0.085916   
Y       0.539548  1.000000 -0.066292 -0.005453 -0.046308  0.007782 -0.101178   
month  -0.065003 -0.066292  1.000000 -0.050837  0.291477  0.466645  0.868698   
day    -0.024922 -0.005453 -0.050837  1.000000 -0.041068  0.062870  0.000105   
FFMC   -0.021039 -0.046308  0.291477 -0.041068  1.000000  0.382619  0.330512   
DMC    -0.048384  0.007782  0.466645  0.062870  0.382619  1.000000  0.682192   
DC     -0.085916 -0.101178  0.868698  0.000105  0.330512  0.682192  1.000000   
ISI     0.006210 -0.024488  0.186597  0.032909  0.531805  0.305128  0.229154   
temp   -0.051258 -0.024103  0.368842  0.052190  0.431532  0.469594  0.496208   
RH      0.085223  0.062221 -0.095280  0.092151 -0.300995  0.073795 -0.039192   
wind    0.018798 -0.020341 -0.086368  0.032478 -0.028485 -0.105342 -0.203466   
rain    0.065387  0.033234  0.013438 -0.048340  0.056702  0.074790  0.035861   
output  0.062491  0.056892  0.130329 -0.042970  0.073823  0.062672  0.096724   

             ISI      temp        RH      wind      rain    output  
X       0.006210 -0.051258  0.085223  0.018798  0.065387  0.062491  
Y      -0.024488 -0.024103  0.062221 -0.020341  0.033234  0.056892  
month   0.186597  0.368842 -0.095280 -0.086368  0.013438  0.130329  
day     0.032909  0.052190  0.092151  0.032478 -0.048340 -0.042970  
FFMC    0.531805  0.431532 -0.300995 -0.028485  0.056702  0.073823  
DMC     0.305128  0.469594  0.073795 -0.105342  0.074790  0.062672  
DC      0.229154  0.496208 -0.039192 -0.203466  0.035861  0.096724  
ISI     1.000000  0.394287 -0.132517  0.106826  0.067668  0.035663  
temp    0.394287  1.000000 -0.527390 -0.227116  0.069491  0.076047  
RH     -0.132517 -0.527390  1.000000  0.069410  0.099751 -0.035587  
wind    0.106826 -0.227116  0.069410  1.000000  0.061119  0.055702  
rain    0.067668  0.069491  0.099751  0.061119  1.000000  0.025550  
output  0.035663  0.076047 -0.035587  0.055702  0.025550  1.000000

In [12]:
#sorting to see which attribute is correlated more to attribut "output" 
fires.corr()['output'].sort_values()
#we can see that attribute "month" is the mostly correlated  to attribute "output"

day      -0.042970
RH       -0.035587
rain      0.025550
ISI       0.035663
wind      0.055702
Y         0.056892
X         0.062491
DMC       0.062672
FFMC      0.073823
temp      0.076047
DC        0.096724
month     0.130329
output    1.000000
Name: output, dtype: float64

In [13]:
from sklearn.preprocessing import StandardScaler
#standardization of data
#removing the mean and scaling it to unit variance
#score=(x-mean)/std
scaler = StandardScaler()
#fitting forest fire dataset to scaler by removing the attribute output
scaler.fit(fires.drop('output',axis=1))

scaled_features = scaler.transform(fires.drop('output',axis=1))
df_feat = pd.DataFrame(scaled_features,columns=fires.columns[:-1])
df_feat.head()
     

X         Y     month       day      FFMC       DMC        DC  \
0  1.008313  0.569860 -1.968443  0.357721 -0.805959 -1.323326 -1.830477   
1  1.008313 -0.244001  1.110120 -1.090909 -0.008102 -1.179541  0.488891   
2  1.008313 -0.244001  1.110120  0.840597 -0.008102 -1.049822  0.560715   
3  1.440925  1.383722 -1.968443  0.357721  0.191362 -1.212361 -1.898266   
4  1.440925  1.383722 -1.968443  1.323474 -0.243833 -0.931043 -1.798600   

        ISI      temp        RH      wind      rain  
0 -0.860946 -1.842640  0.411724  1.498614 -0.073268  
1 -0.509688 -0.153278 -0.692456 -1.741756 -0.073268  
2 -0.509688 -0.739383 -0.692456 -1.518282 -0.073268  
3 -0.004756 -1.825402  3.233519 -0.009834  0.603155  
4  0.126966 -1.291012  3.356206 -1.238940 -0.073268

In [14]:
from sklearn.model_selection import train_test_split
X = df_feat
y = fires['output']
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.35,random_state=200)

In [15]:

#importing logistic regression
from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression()
logistic_model.fit(X_train,y_train)

predictions = logistic_model.predict(X_test)

#finding precision,recall,accuracy
print("Precision:",metrics.precision_score(y_test, predictions))
print("Recall:",metrics.recall_score(y_test, predictions))
print("Accuracy:",metrics.accuracy_score(y_test, predictions))

print(confusion_matrix(y_test,predictions))

Precision: 0.5462184873949579
Recall: 0.7142857142857143
Accuracy: 0.5580110497237569
[[36 54]
 [26 65]]


In [16]:
#prediction using logistic regression
class_label={1:'There is Fire',0:'There is no fire'}
x_new=[[1, 4, 9 ,1 ,91.5, 130.1, 807.1, 7.5, 21.3, 35, 2.2, 0]]


y_predict=logistic_model.predict(x_new)
print(class_label[y_predict[0]])

There is no fire


In [17]:
#importing k nearest neighbour
from sklearn.neighbors import KNeighborsClassifier
k_nearest_neighbor_model = KNeighborsClassifier(n_neighbors=1)
k_nearest_neighbor_model.fit(X_train,y_train)
pred = k_nearest_neighbor_model.predict(X_test)

In [18]:
knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train,y_train)
pred = knn.predict(X_test)
print('WITH K=7')
print('\n')
print(confusion_matrix(y_test,pred))

     

WITH K=7


[[42 48]
 [42 49]]


In [19]:
knn = KNeighborsClassifier(n_neighbors=17)
knn.fit(X_train,y_train)
pred = knn.predict(X_test)
print('WITH K=17')
print('\n')
print(confusion_matrix(y_test,pred))

WITH K=17


[[37 53]
 [34 57]]


In [28]:
knn.score(X_test, y_test)

0.5193370165745856

In [29]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, pred))
print("Precision:",metrics.precision_score(y_test, pred))
print("Recall:",metrics.recall_score(y_test, pred))
     

Accuracy: 0.5193370165745856
Precision: 0.5181818181818182
Recall: 0.6263736263736264


In [23]:
#prediction using knn
classes={0:'safe',1:'On Fire'}
x_new=[[5, 9, 6,45 ,91.5, 130.1, 07.1, 7.5, 21.3, 35, 2.2, 0]]
y_predict=knn.predict(x_new)
print(classes[y_predict[0]])
     

On Fire


In [20]:
# Support Vector Machine
from sklearn.svm import SVC

# fit a SVM model to the data

X = fires.drop('output', axis=1)
y = fires['output']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3,random_state=101)

svc = SVC()
svc.fit(X_train, y_train)
# make predictions
prediction = svc.predict(X_test)

print(metrics.confusion_matrix(y_test, prediction))

print("Accuracy:",metrics.accuracy_score(y_test, prediction))
print("Precision:",metrics.precision_score(y_test, prediction))
print("Recall:",metrics.recall_score(y_test, prediction))


[[20 49]
 [11 76]]
Accuracy: 0.6153846153846154
Precision: 0.608
Recall: 0.8735632183908046


In [21]:
#prediction using svm
classes={0:'safe',1:'On Fire'}
x_new=[[1, 4, 9 ,1 ,91.5, 130.1, 807.1, 7.5, 21.3, 35, 2.2, 0]]
y_predict=svc.predict(x_new)
print(classes[y_predict[0]])

On Fire
